[package]
name = "maat"
version = "0.1.0"
edition = "2021"

[dependencies]
dynamic = "0.2.1"
radamsa = "0.1.1"
rand = { version = "0.8.5", features = ["small_rng"] }
rand_xoshiro = { version = "0.6.0", features = ["serde1"] }
serde = "1.0.144"
serde_json = "1.0.85"
